// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApM6VZ0rnYw7Bo7ARXLt-OaxMstDCbowA',
    appId: '1:134925967172:web:4b68332f0c1e9971824111',
    messagingSenderId: '134925967172',
    projectId: 'flutter-test-4e4ed',
    authDomain: 'flutter-test-4e4ed.firebaseapp.com',
    storageBucket: 'flutter-test-4e4ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu-TjHf1nVLpTBb-mWl6e_KemEiwhAclM',
    appId: '1:134925967172:android:66741dd92686587a824111',
    messagingSenderId: '134925967172',
    projectId: 'flutter-test-4e4ed',
    storageBucket: 'flutter-test-4e4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNXo4DFufN4V7ZlZDgRkIUIbflPRuxUq0',
    appId: '1:134925967172:ios:4623ac1390cb0387824111',
    messagingSenderId: '134925967172',
    projectId: 'flutter-test-4e4ed',
    storageBucket: 'flutter-test-4e4ed.appspot.com',
    iosClientId: '134925967172-m976qglbugerv2jmp6bomj50d7v9sivu.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudproyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNXo4DFufN4V7ZlZDgRkIUIbflPRuxUq0',
    appId: '1:134925967172:ios:656258d58a56f5ee824111',
    messagingSenderId: '134925967172',
    projectId: 'flutter-test-4e4ed',
    storageBucket: 'flutter-test-4e4ed.appspot.com',
    iosClientId: '134925967172-2g5s701pdrsdfu4nf67qoai4f3323gdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudproyecto.RunnerTests',
  );
}
